/**
 * Data processing module
 * Combines internet and space objects data with country codes
 */

const DATA = {
    // Country data: combines internet adoption and space objects
    countries: [
        { code: "AFG", name: "Afghanistan", internet: 17.71, space: 0 },
        { code: "ALB", name: "Albania", internet: 67.9, space: 0 },
        { code: "DZA", name: "Algeria", internet: 47.0, space: 3 },
        { code: "AND", name: "Andorra", internet: 89.5, space: 0 },
        { code: "AGO", name: "Angola", internet: 13.0, space: 1 },
        { code: "ATG", name: "Antigua and Barbuda", internet: 84.0, space: 0 },
        { code: "ARG", name: "Argentina", internet: 79.5, space: 15 },
        { code: "AZE", name: "Azerbaijan", internet: 77.0, space: 0 },
        { code: "BHS", name: "Bahamas", internet: 88.5, space: 0 },
        { code: "BHR", name: "Bahrain", internet: 96.5, space: 0 },
        { code: "BGD", name: "Bangladesh", internet: 35.0, space: 0 },
        { code: "BRB", name: "Barbados", internet: 86.5, space: 0 },
        { code: "BLR", name: "Belarus", internet: 87.0, space: 0 },
        { code: "BEL", name: "Belgium", internet: 94.0, space: 3 },
        { code: "BLZ", name: "Belize", internet: 60.5, space: 0 },
        { code: "BEN", name: "Benin", internet: 28.8, space: 0 },
        { code: "BTN", name: "Bhutan", internet: 52.0, space: 0 },
        { code: "BOL", name: "Bolivia", internet: 30.5, space: 0 },
        { code: "BIH", name: "Bosnia and Herzegovina", internet: 82.0, space: 0 },
        { code: "BWA", name: "Botswana", internet: 33.0, space: 0 },
        { code: "BRA", name: "Brazil", internet: 88.5, space: 20 },
        { code: "BRN", name: "Brunei", internet: 91.5, space: 0 },
        { code: "BGR", name: "Bulgaria", internet: 84.0, space: 0 },
        { code: "BFA", name: "Burkina Faso", internet: 23.5, space: 0 },
        { code: "BDI", name: "Burundi", internet: 19.5, space: 0 },
        { code: "KHM", name: "Cambodia", internet: 41.3, space: 0 },
        { code: "CMR", name: "Cameroon", internet: 32.5, space: 0 },
        { code: "CAN", name: "Canada", internet: 93.0, space: 150 },
        { code: "CPV", name: "Cape Verde", internet: 62.0, space: 0 },
        { code: "CAF", name: "Central African Republic", internet: 14.0, space: 0 },
        { code: "TCD", name: "Chad", internet: 9.5, space: 0 },
        { code: "CHL", name: "Chile", internet: 89.0, space: 2 },
        { code: "CHN", name: "China", internet: 73.0, space: 63 },
        { code: "COL", name: "Colombia", internet: 65.5, space: 3 },
        { code: "COM", name: "Comoros", internet: 23.0, space: 0 },
        { code: "COG", name: "Congo", internet: 21.5, space: 0 },
        { code: "COD", name: "Dem. Rep. Congo", internet: 13.0, space: 0 },
        { code: "CRI", name: "Costa Rica", internet: 78.0, space: 0 },
        { code: "HRV", name: "Croatia", internet: 87.0, space: 0 },
        { code: "CUB", name: "Cuba", internet: 46.5, space: 0 },
        { code: "CYP", name: "Cyprus", internet: 91.5, space: 0 },
        { code: "CZE", name: "Czechia", internet: 88.5, space: 0 },
        { code: "CIV", name: "Côte d'Ivoire", internet: 35.5, space: 0 },
        { code: "DNK", name: "Denmark", internet: 96.0, space: 5 },
        { code: "DJI", name: "Djibouti", internet: 44.0, space: 0 },
        { code: "DMA", name: "Dominica", internet: 77.3, space: 0 },
        { code: "DOM", name: "Dominican Republic", internet: 63.0, space: 0 },
        { code: "ECU", name: "Ecuador", internet: 55.0, space: 0 },
        { code: "EGY", name: "Egypt", internet: 38.0, space: 0 },
        { code: "SLV", name: "El Salvador", internet: 36.0, space: 0 },
        { code: "GNQ", name: "Equatorial Guinea", internet: 33.0, space: 0 },
        { code: "ERI", name: "Eritrea", internet: 4.0, space: 0 },
        { code: "EST", name: "Estonia", internet: 92.6, space: 0 },
        { code: "ETH", name: "Ethiopia", internet: 20.8, space: 0 },
        { code: "FJI", name: "Fiji", internet: 61.0, space: 0 },
        { code: "FIN", name: "Finland", internet: 95.0, space: 21 },
        { code: "FRA", name: "France", internet: 92.0, space: 35 },
        { code: "GAB", name: "Gabon", internet: 49.0, space: 0 },
        { code: "GMB", name: "Gambia", internet: 38.8, space: 0 },
        { code: "GEO", name: "Georgia", internet: 81.5, space: 0 },
        { code: "DEU", name: "Germany", internet: 94.0, space: 35 },
        { code: "GHA", name: "Ghana", internet: 56.5, space: 0 },
        { code: "GRC", name: "Greece", internet: 91.0, space: 6 },
        { code: "GRD", name: "Grenada", internet: 78.5, space: 0 },
        { code: "GTM", name: "Guatemala", internet: 41.5, space: 0 },
        { code: "GIN", name: "Guinea", internet: 37.0, space: 0 },
        { code: "GNB", name: "Guinea-Bissau", internet: 35.5, space: 0 },
        { code: "GUY", name: "Guyana", internet: 49.0, space: 0 },
        { code: "HTI", name: "Haiti", internet: 12.0, space: 0 },
        { code: "HND", name: "Honduras", internet: 40.0, space: 0 },
        { code: "HKG", name: "Hong Kong", internet: 94.5, space: 0 },
        { code: "HUN", name: "Hungary", internet: 90.0, space: 1 },
        { code: "ISL", name: "Iceland", internet: 98.5, space: 1 },
        { code: "IND", name: "India", internet: 45.0, space: 28 },
        { code: "IDN", name: "Indonesia", internet: 51.5, space: 0 },
        { code: "IRN", name: "Iran", internet: 60.0, space: 0 },
        { code: "IRQ", name: "Iraq", internet: 36.5, space: 0 },
        { code: "IRL", name: "Ireland", internet: 96.0, space: 6 },
        { code: "ISR", name: "Israel", internet: 92.8, space: 12 },
        { code: "ITA", name: "Italy", internet: 93.5, space: 8 },
        { code: "JAM", name: "Jamaica", internet: 71.0, space: 0 },
        { code: "JPN", name: "Japan", internet: 83.0, space: 48 },
        { code: "JOR", name: "Jordan", internet: 76.0, space: 0 },
        { code: "KAZ", name: "Kazakhstan", internet: 78.5, space: 0 },
        { code: "KEN", name: "Kenya", internet: 44.0, space: 0 },
        { code: "KIR", name: "Kiribati", internet: 35.0, space: 0 },
        { code: "PRK", name: "North Korea", internet: 7.0, space: 0 },
        { code: "KOR", name: "South Korea", internet: 90.0, space: 12 },
        { code: "KWT", name: "Kuwait", internet: 94.0, space: 0 },
        { code: "KGZ", name: "Kyrgyzstan", internet: 41.0, space: 0 },
        { code: "LAO", name: "Laos", internet: 27.0, space: 0 },
        { code: "LVA", name: "Latvia", internet: 91.0, space: 0 },
        { code: "LBN", name: "Lebanon", internet: 78.5, space: 0 },
        { code: "LSO", name: "Lesotho", internet: 28.0, space: 0 },
        { code: "LBR", name: "Liberia", internet: 13.5, space: 0 },
        { code: "LBY", name: "Libya", internet: 45.0, space: 0 },
        { code: "LIE", name: "Liechtenstein", internet: 98.0, space: 0 },
        { code: "LTU", name: "Lithuania", internet: 92.5, space: 0 },
        { code: "LUX", name: "Luxembourg", internet: 96.5, space: 0 },
        { code: "MAC", name: "Macao", internet: 93.0, space: 0 },
        { code: "MDG", name: "Madagascar", internet: 17.0, space: 0 },
        { code: "MWI", name: "Malawi", internet: 11.5, space: 0 },
        { code: "MYS", name: "Malaysia", internet: 89.0, space: 0 },
        { code: "MDV", name: "Maldives", internet: 89.5, space: 0 },
        { code: "MLI", name: "Mali", internet: 20.0, space: 0 },
        { code: "MLT", name: "Malta", internet: 95.0, space: 0 },
        { code: "MHL", name: "Marshall Islands", internet: 34.0, space: 0 },
        { code: "MRT", name: "Mauritania", internet: 32.5, space: 0 },
        { code: "MUS", name: "Mauritius", internet: 71.0, space: 0 },
        { code: "MEX", name: "Mexico", internet: 68.5, space: 3 },
        { code: "FSM", name: "Micronesia", internet: 35.5, space: 0 },
        { code: "MDA", name: "Moldova", internet: 79.0, space: 0 },
        { code: "MCO", name: "Monaco", internet: 95.0, space: 0 },
        { code: "MNG", name: "Mongolia", internet: 65.5, space: 0 },
        { code: "MNE", name: "Montenegro", internet: 83.5, space: 0 },
        { code: "MAR", name: "Morocco", internet: 66.5, space: 0 },
        { code: "MOZ", name: "Mozambique", internet: 28.0, space: 0 },
        { code: "MMR", name: "Myanmar", internet: 29.5, space: 0 },
        { code: "NAM", name: "Namibia", internet: 49.5, space: 0 },
        { code: "NRU", name: "Nauru", internet: 85.0, space: 0 },
        { code: "NPL", name: "Nepal", internet: 28.0, space: 0 },
        { code: "NLD", name: "Netherlands", internet: 96.0, space: 25 },
        { code: "NZL", name: "New Zealand", internet: 93.5, space: 9 },
        { code: "NIC", name: "Nicaragua", internet: 39.5, space: 0 },
        { code: "NER", name: "Niger", internet: 15.0, space: 0 },
        { code: "NGA", name: "Nigeria", internet: 36.0, space: 0 },
        { code: "NOR", name: "Norway", internet: 98.0, space: 8 },
        { code: "OMN", name: "Oman", internet: 81.0, space: 0 },
        { code: "PAK", name: "Pakistan", internet: 27.5, space: 0 },
        { code: "PLW", name: "Palau", internet: 74.0, space: 0 },
        { code: "PAN", name: "Panama", internet: 55.5, space: 0 },
        { code: "PNG", name: "Papua New Guinea", internet: 14.5, space: 0 },
        { code: "PRY", name: "Paraguay", internet: 78.5, space: 0 },
        { code: "PER", name: "Peru", internet: 60.0, space: 2 },
        { code: "PHL", name: "Philippines", internet: 62.0, space: 0 },
        { code: "POL", name: "Poland", internet: 89.0, space: 1 },
        { code: "PRT", name: "Portugal", internet: 91.0, space: 1 },
        { code: "QAT", name: "Qatar", internet: 96.0, space: 0 },
        { code: "ROU", name: "Romania", internet: 83.5, space: 0 },
        { code: "RUS", name: "Russia", internet: 88.5, space: 38 },
        { code: "RWA", name: "Rwanda", internet: 32.5, space: 0 },
        { code: "KNA", name: "St. Kitts and Nevis", internet: 82.5, space: 0 },
        { code: "LCA", name: "St. Lucia", internet: 80.5, space: 0 },
        { code: "VCT", name: "St. Vincent & Grenadines", internet: 76.0, space: 0 },
        { code: "WSM", name: "Samoa", internet: 55.0, space: 0 },
        { code: "SMR", name: "San Marino", internet: 90.0, space: 0 },
        { code: "STP", name: "São Tomé & Príncipe", internet: 42.0, space: 0 },
        { code: "SAU", name: "Saudi Arabia", internet: 83.0, space: 0 },
        { code: "SEN", name: "Senegal", internet: 47.0, space: 0 },
        { code: "SRB", name: "Serbia", internet: 84.0, space: 0 },
        { code: "SYC", name: "Seychelles", internet: 75.5, space: 0 },
        { code: "SLE", name: "Sierra Leone", internet: 38.5, space: 0 },
        { code: "SGP", name: "Singapore", internet: 96.5, space: 0 },
        { code: "SVK", name: "Slovakia", internet: 89.0, space: 0 },
        { code: "SVN", name: "Slovenia", internet: 92.8, space: 0 },
        { code: "SLB", name: "Solomon Islands", internet: 36.5, space: 0 },
        { code: "SOM", name: "Somalia", internet: 26.0, space: 0 },
        { code: "ZAF", name: "South Africa", internet: 65.5, space: 6 },
        { code: "SSD", name: "South Sudan", internet: 9.0, space: 0 },
        { code: "ESP", name: "Spain", internet: 93.5, space: 6 },
        { code: "LKA", name: "Sri Lanka", internet: 34.0, space: 0 },
        { code: "SDN", name: "Sudan", internet: 18.5, space: 0 },
        { code: "SUR", name: "Suriname", internet: 63.5, space: 0 },
        { code: "SWZ", name: "Eswatini", internet: 37.5, space: 0 },
        { code: "SWE", name: "Sweden", internet: 97.0, space: 18 },
        { code: "CHE", name: "Switzerland", internet: 97.0, space: 3 },
        { code: "SYR", name: "Syria", internet: 19.5, space: 0 },
        { code: "TWN", name: "Taiwan", internet: 88.5, space: 0 },
        { code: "TJK", name: "Tajikistan", internet: 35.0, space: 0 },
        { code: "TZA", name: "Tanzania", internet: 28.5, space: 0 },
        { code: "THA", name: "Thailand", internet: 84.5, space: 0 },
        { code: "TLS", name: "Timor-Leste", internet: 23.5, space: 0 },
        { code: "TGO", name: "Togo", internet: 45.5, space: 0 },
        { code: "TON", name: "Tonga", internet: 53.5, space: 0 },
        { code: "TTO", name: "Trinidad and Tobago", internet: 80.5, space: 1 },
        { code: "TUN", name: "Tunisia", internet: 61.0, space: 0 },
        { code: "TUR", name: "Turkey", internet: 82.0, space: 1 },
        { code: "TKM", name: "Turkmenistan", internet: 25.5, space: 0 },
        { code: "TUV", name: "Tuvalu", internet: 65.0, space: 0 },
        { code: "UGA", name: "Uganda", internet: 21.5, space: 0 },
        { code: "UKR", name: "Ukraine", internet: 81.5, space: 0 },
        { code: "ARE", name: "United Arab Emirates", internet: 99.0, space: 0 },
        { code: "GBR", name: "United Kingdom", internet: 96.8, space: 35 },
        { code: "USA", name: "United States", internet: 90.0, space: 210 },
        { code: "URY", name: "Uruguay", internet: 87.5, space: 0 },
        { code: "UZB", name: "Uzbekistan", internet: 38.0, space: 0 },
        { code: "VUT", name: "Vanuatu", internet: 43.5, space: 0 },
        { code: "VEN", name: "Venezuela", internet: 49.0, space: 0 },
        { code: "VNM", name: "Vietnam", internet: 71.0, space: 0 },
        { code: "YEM", name: "Yemen", internet: 25.0, space: 0 },
        { code: "ZMB", name: "Zambia", internet: 21.5, space: 0 },
        { code: "ZWE", name: "Zimbabwe", internet: 18.5, space: 0 }
    ]
};

// World GeoJSON URL
const WORLD_GEOJSON_URL = "https://raw.githubusercontent.com/holtzy/D3-graph-gallery/master/DATA/world.geojson";
